# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hey
email: jzxwong@gmail.com
description: Zhixun Wang (Jason or 王志詢 in Chinese)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wangzhixun.com" # the base hostname & protocol for your site
twitter_username: ZhixunWang
github_username:  zhixunwang

# Build settings
markdown: kramdown
