
# SEO settings
title: "An"
title2: " Island" # default: ""
description: "I post stuff I found interesting here."
keywords: "R, analytics, data science, 中文, 生活, blog"
url: http://wangzhixun.com/ # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
# repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "wangzhixun"
twitter_username: "ZhixunWang"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge
include: ['_pages']

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Zhixun Wang"
  job      : "curious person"
  bio      : "I am a survivor."
  thumb    : /images/author.jpg
  email    : jzxwong@gmail.com
  url      : http://wangzhixun.com
  github   : https://github.com/zhixunwang
  twitter  : http://twitter.com/ZhixunWang
  # facebook : https://www.facebook.com/
  linkedin : http://linkedin.com/in/wangzhixun

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@ZhixunWang"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : science
    title: Science

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
