# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: An Island
email: jzxwong@gmail.com
description: 
keywords:     demo theme example github jekyll features
language:     "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wangzhixun.com" # the base hostname & protocol for your site
permalink:    /blog/:categories/:title
#cover:        /assets/mountain-cover.jpg
twitter_username: ZhixunWang
github_username:  zhixunwang
comments: true

# Build settings
markdown: kramdown
#kramdown:
#  syntax_highlighter_opts:
#    disable: false
highlighter: rouge
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from